### ISSUE TITLE
Add support for dual variable Layer keycodes

### ISSUE THREAD

**Issue by drashna** [qmk/qmk_configurator#117]
Namely LT(x, kc), and LM(x, mod).  Both require 2 variables (layer and mod/keycode). 

IIRC, configurator doesn't support multiple inputs, yet

**Comment by newtonapple** [comment]
Is there a timeline for supporting LT & LM?  I personally use LT a lot, it'd be great to be able use these through the graphical configurator, like how they have it on qmkeyboard.cn or kbfirmware.com.

**Comment by yanfali** [comment]
Nope, sorry. You can kind of use it now using ANY. It should work, though I
haven't tested it recently.

**Comment by newtonapple** [comment]
How does `ANY` work?  Do you just type in, for example: `LT(1,KC_SPC),` in the text box? When I tried that, it gave me the follow error:

```
Traceback (most recent call last):
  File "./qmk_compiler.py", line 178, in compile_firmware
    create_keymap(result, layers)
  File "./qmk_compiler.py", line 96, in create_keymap
    keymap_c = generate_keymap_c(result, layers)
  File "./qmk_compiler.py", line 44, in generate_keymap_c
    layer_keys = ', '.join(layer)
TypeError: sequence item 64: expected str instance, NoneType found
```

**Comment by dtanner** [comment]
FWIW the `ANY` config worked fine for me using as an example `LT(1,KC_ESCAPE)`.  
Maybe it's been fixed since the above error was noted.

**Comment by yanfali** [comment]
Thanks for confirming

**Comment by yanfali** [comment]
Half of this is now available via LT 971dee0f8200e2bfde5f595a5599aff3246d1927, are people still looking for LM support?

**Comment by PhoenSXar** [comment]
I'm still looking for LM support.I use dvorak layout and I create a map from dvorak to qwerty in a layer.
LM(mapLayer, ctrl) is so much convenient to use all keyboard shortcut.

**Comment by yanfali** [comment]
@PhoenSXar hi there. This is a pretty tricky feature to implement in the UI because it's combinatorial. I have some ideas on how to do it, but it would require quite a lot of effort for something I'm not sure is used that frequently. I'll keep thinking about it though.

e.g. `LM(4, MOD_LCTRL | MOD_LSFT)`

My recommendation at this time is use the ANY keycode and just input what you need.

**Comment by PhoenSXar** [comment]
@yanfali Thanks, I will use the ANY keycode to make it work. As I examine this repo in greater detail, maybe I will submit a PR that time. By then, let's thinking about it :).
