### ISSUE TITLE
[Bug] Error on compile

### ISSUE THREAD

**Issue by chiwou** [qmk/qmk_configurator#931]
## Describe the Bug

At the end of the compile I get an error

## Additional Context

actual error text
```
Warning: The bin/qmk script is being deprecated. Please install the QMK CLI: python3 -m pip install qmk
Traceback (most recent call last):
  File "bin/qmk", line 57, in <module>
    main()
  File "bin/qmk", line 38, in main
    import qmk.cli  # noqa
  File "/qmk_compiler/qmk_firmware/lib/python/qmk/cli/__init__.py", line 158, in <module>
    from . import console  # noqa
  File "/qmk_compiler/qmk_firmware/lib/python/qmk/cli/console.py", line 9, in <module>
    import hid
ModuleNotFoundError: No module named 'hid'
```

Tried it with different keyboards

- massdrop/alt
- kbdfans/kbd67
- alpine65

always the same result

**Comment by skullydazed** [comment]
This should be fixed now.

**Comment by chiwou** [comment]
👍
